ALTER TABLE channel_models ADD COLUMN input_usage INTEGER NOT NULL DEFAULT 0;
ALTER TABLE channel_models ADD COLUMN outpu_usage INTEGER NOT NULL DEFAULT 0;
ALTER TABLE channel_models ADD COLUMN total_cost INTEGER NOT NULL DEFAULT 0;
